#!/usr/bin/env bash

# Check if an IP address is provided as an argument
if [ $# -ne 0 ]; then
  echo "Usage: 5-is_the_host_on_the_network"
  exit 1
fi

# Extract the IP address from the argument
ip_address="$1"

# Ping the IP address 5 times
ping -c 5 -i 1 "$ip_address"
